### ISSUE TITLE
Add option to use Shannon Entropy

### ISSUE THREAD

**Issue by yanchith** [subdgtl/WFC#13]
Currently we use the simplest possible entropy metric - linear entropy from 0 (for zero modules) to N (for all modules).

For some rulesets this produces worlds that are very hard to collapse to a deterministic state. This is because all modules are treated equally, even if some modules are more picky as to what their neighbors can be than others.

For Shannon Entropy we assign a weight for every module. Because we construct the rules directly and do not scan exemplary data, the weight of a module will be determined by its frequency in the ruleset, and not in the sample data.

Biasing the slot choice with weighted entropy should mean that slots containing the more picky modules are observed with a higher priority.

**Comment by janper** [comment]
The description doesn't explicitly say so, but I'd add that the entropy is only used for picking the slots to observe: slots containing modules with lower entropy (cumulative, minimum, maximum, average) are observed first. The choice of a Module in the observed slot should remain random.

**Comment by yanchith** [comment]
You are right, of course! But it might be interesting to explore biased module choice too once we are done with this.

> slots containing modules with lower entropy (cumulative, minimum, maximum, average)

Hmm, I only thought of cumulative, but the others might be fun to play with too.

**Comment by yanchith** [comment]
Did the initial impl. So far it looks like this:

- Linear Entropy has regressed in wall time speed by about 5-13% (depending on world size)
- Shannon Entropy is about 30-70% slower than original linear entropy (depending on world size)

However, Shannon Entropy seems to be having a much easier time finding correct solutions. I need to test on more complicated rulesets to confirm, but on the simple `sample3.csv`, it actually finished a little faster because it required less attempts.

**Comment by janper** [comment]
1. can it be already tested on Monoceros or should we stick to the standalone app?
2. do I get it right that there are still both approaches to the entropy available? if so, why not letting the user choose? or implement some smart autoswitch in C#

**Comment by yanchith** [comment]
1) It can't be tested in Monoceros yet, but not much work remains. I'll do that tomorrow. That should help us validate result quality. Also to ease my regression testing and benchmarking, I'll export some rulesets from Monoceros examples to the text format (I hope that's possible to do somehow).
2) Yes, both are available, because they produce different results and provide different tradeoffs. It is not clear at the moment if Shannon Entropy is always superior. Exactly as you say, we can either let the C# solver or the end user decide. This library will always give you the choice.

**Comment by janper** [comment]
1. testing in Monoceros is the way. export is possible but not worth the effort. you can DIY though, just look at my summer solver.
2. cool. we need to figure out the signs that the linear entropy is not the right approach and then auto switch to Shannon. am I correct that we can count the number of observations on C# now?

**Comment by janper** [comment]
my hunch is that either too few or too many observations before contradiction indicate we need to use a different approach to the entropy
