### ISSUE TITLE
Report reason for contradictory state

### ISSUE THREAD

**Issue by janper** [subdgtl/WFC#23]
This is an issue when the world state is contradictory at the very beginning  - the contradiction is already in the initial state.

Would it be possible to report which disallowed connection cause the contradiction or rather where did the contradiction occur?

**Comment by yanchith** [comment]
You can already get it with `wfc_world_state_slots_get` after doing `wfc_world_state_slots_set`. This functionality will also be preserved with the switch to new get/set API.
