### ISSUE TITLE
When wfc_world_state_free is called for a wrong address, it crashes without any message.

### ISSUE THREAD

**Issue by janper** [subdgtl/WFC#26]
When `wfc_world_state_free` is called for a wrong address, it crashes Rhino without any message.
This only happens during development and it took me a while (actually it was my first guess) to realize where does the crash occur.

**Comment by yanchith** [comment]
That is correct. It even says so in the documentation: https://github.com/subdgtl/WFC/blob/master/wfc_dylib/ffi/wfc.hpp#L265

On a more serious note, I understand this makes development unpleasant, but how would you handle this? Imagine you have a function that receives any memory address as a parameter. How would you know the address points to valid memory you previously created without spending resources on tracking it?

**Comment by janper** [comment]
I thought so, actually
